/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountIcon: typeof import('./src/components/icons/AccountIcon.vue')['default']
    AccountIcon_: typeof import('./src/components/icons/AccountIcon_.vue')['default']
    AddIcon: typeof import('./src/components/icons/AddIcon.vue')['default']
    AuthModal: typeof import('./src/components/auth/AuthModal.vue')['default']
    BaseCard: typeof import('./src/components/BaseCard.vue')['default']
    BookIcon: typeof import('./src/components/icons/BookIcon.vue')['default']
    ChatIcon: typeof import('./src/components/icons/ChatIcon.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    ChatSidebar: typeof import('./src/components/chat/ChatSidebar.vue')['default']
    CheckCircleIcon: typeof import('./src/components/icons/CheckCircleIcon.vue')['default']
    DashboardIcon: typeof import('./src/components/icons/DashboardIcon.vue')['default']
    DdlNews: typeof import('./src/components/DdlNews.vue')['default']
    EmailIcon: typeof import('./src/components/icons/EmailIcon.vue')['default']
    InfoCircleIcon: typeof import('./src/components/icons/InfoCircleIcon.vue')['default']
    LocationIcon: typeof import('./src/components/icons/LocationIcon.vue')['default']
    PhoneIcon: typeof import('./src/components/icons/PhoneIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShieldIcon: typeof import('./src/components/icons/ShieldIcon.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SimpleCalendar: typeof import('./src/components/SimpleCalendar.vue')['default']
    TargetIcon: typeof import('./src/components/icons/TargetIcon.vue')['default']
    UserSettings: typeof import('./src/components/user/UserSettings.vue')['default']
    WelcomeScreen: typeof import('./src/components/chat/WelcomeScreen.vue')['default']
  }
}
