# 创建数据库中所需表格的SQL语句

CREATE TABLE `比赛通知` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `比赛开始时间` DATETIME,
  `比赛结束时间` DATETIME,
  `报名截止时间` DATETIME,
  `主办方` VARCHAR(100),
  `比赛地点` VARCHAR(255),
  `比赛名称` VARCHAR(255) NOT NULL,
  `比赛级别、形式` VARCHAR(255),
  `比赛主题` VARCHAR(255),
  `参赛资格` VARCHAR(255),
  `技能需求` VARCHAR(255),
  `比赛奖励` VARCHAR(255),
  `报名费用` VARCHAR(50),
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `学习资源` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `资源类型` VARCHAR(255),
  `提供单位` VARCHAR(255),
  `适用场景` VARCHAR(255),
  `访问方式` VARCHAR(255),
  `使用权限_身份` VARCHAR(255),
  `使用权限_学院` VARCHAR(255),
  `使用权限_设备` VARCHAR(255),
  `功能描述` TEXT,
  `是否需费用` BIT(1),
  `有效期至` DATETIME,
  `技术支持` VARCHAR(255),
  `关联服务` VARCHAR(255),
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `校园通知` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `通知性质` VARCHAR(255),
  `核心对象` VARCHAR(255),
  `相关服务、区域` VARCHAR(255),
  `生效时间` DATETIME,
  `截止时间` VARCHAR(50),
  `责任部门` VARCHAR(255),
  `核心摘要` TEXT,
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `学业申请` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `政策名称` VARCHAR(255) NOT NULL,
  `生效时间` DATETIME,
  `过期时间` DATETIME,
  `适用对象` VARCHAR(255),
  `政策类别` VARCHAR(255),
  `发布部门` VARCHAR(255),
  `政策级别` VARCHAR(50),
  `GPA要求` VARCHAR(50),
  `学分要求` VARCHAR(255),
  `其他要求` VARCHAR(255),
  `特定课程门槛` VARCHAR(255),
  `申请步骤` VARCHAR(255),
  `申请起始日期` DATETIME,
  `申请截止时间` DATETIME,
  `相关材料` VARCHAR(255),
  `相关政策` VARCHAR(255),
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `学业相关政策` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `政策名称` VARCHAR(255) NOT NULL,
  `生效时间` DATETIME,
  `过期时间` DATETIME,
  `发布部门` VARCHAR(255),
  `适用对象` VARCHAR(255),
  `政策类别` VARCHAR(255),
  `核心条款` VARCHAR(255),
  `关联系统` VARCHAR(255),
  `系统操作指南链接` VARCHAR(255),
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `奖励、资助政策` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `政策名称` VARCHAR(255) NOT NULL,
  `政策类别` VARCHAR(255),
  `适用年度` VARCHAR(50),
  `奖励内容` VARCHAR(255),
  `适用对象` VARCHAR(255),
  `评定维度_学业成绩` VARCHAR(255),
  `评定维度_科研创新` VARCHAR(255),
  `评定维度_社会实践` VARCHAR(255),
  `其他评定方法` VARCHAR(255),
  `硬性否决条件_学业` VARCHAR(255),
  `硬性否决条件_纪律` VARCHAR(255),
  `是否需要答辩` BIT(1),
  `材料清单` VARCHAR(255),
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `惩罚制度` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `政策名称` VARCHAR(255) NOT NULL,
  `政策类别` VARCHAR(255),
  `适用对象` VARCHAR(255),
  `处罚等级体系` VARCHAR(255),
  `影响范围_评奖评优` VARCHAR(255),
  `影响范围_保研资格` VARCHAR(255),
  `关联政策` VARCHAR(255),
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `校园安全` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `政策名称` VARCHAR(255) NOT NULL,
  `政策类别` VARCHAR(255),
  `管理对象类型` VARCHAR(255),
  `责任主体` VARCHAR(255),
  `适用对象` VARCHAR(255),
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `讲座或分享会信息` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `讲座起始时间` DATETIME,
  `讲座结束时间` DATETIME,
  `地点` VARCHAR(255),
  `线上参会链接或腾讯会议号` VARCHAR(255),
  `讲座类型` VARCHAR(255),
  `讲座领域` VARCHAR(255),
  `是否需要报名` BIT(1),
  `五育认定类型` VARCHAR(50),
  `报名截止时间` DATETIME,
  `主讲人信息` TEXT,
  `适用年级` VARCHAR(255),
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `志愿活动` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `主办单位` VARCHAR(255),
  `服务起始时间` DATETIME,
  `服务结束时间` DATETIME,
  `服务地点类型` VARCHAR(50),
  `详细地址` VARCHAR(255),
  `线上服务方式` VARCHAR(255),
  `志愿类型` VARCHAR(255),
  `志愿时长_小时` VARCHAR(50),
  `招募人数` INT,
  `单次或长期` VARCHAR(50),
  `技能要求` VARCHAR(255),
  `是否培训` BIT(1),
  `报名截止时间` DATETIME,
  `面向群体` VARCHAR(255),
  `是否提供证书` BIT(1),
  `特殊福利` VARCHAR(255),
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `社会实践` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `类型` VARCHAR(50) NOT NULL,
  `标题` VARCHAR(255) NOT NULL,
  `活动开始时间` DATETIME,
  `活动结束时间` DATETIME,
  `报名截止时间` DATETIME,
  `主办单位` VARCHAR(255),
  `活动地点` VARCHAR(255),
  `活动主题` VARCHAR(255),
  `实践形式` VARCHAR(255),
  `组队要求` VARCHAR(255),
  `参与对象` VARCHAR(255),
  `学分认定` VARCHAR(50),
  `经费支持` VARCHAR(255),
  `报名方式` VARCHAR(255),
  `技能需求` VARCHAR(255),
  `考核标准` VARCHAR(255),
  `关联课程` VARCHAR(255),
  `咨询方式` VARCHAR(255),
  `原文信息` TEXT,
  `发布日期` DATE,
  `关键词` VARCHAR(255),
  `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `国际交流项目` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `类型` VARCHAR(50) NOT NULL,
    `标题` VARCHAR(255) NOT NULL,
    `项目名称` VARCHAR(255) NOT NULL,
    `项目类别` VARCHAR(255),
    `合作国家地区` VARCHAR(100),
    `合作院校机构` VARCHAR(255),
    `项目申请截止时间` DATETIME,
    `项目开始日期` DATETIME,
    `项目结束日期` DATETIME,
    `项目时长描述` VARCHAR(255),
    `学科领域` VARCHAR(255),
    `申请资格_学历` VARCHAR(255),
    `申请资格_GPA` VARCHAR(50),
    `申请资格_其他` VARCHAR(255),
    `语言要求_英语` VARCHAR(255),
    `语言要求_小语种` VARCHAR(255),
    `选拔标准` VARCHAR(255),
    `申请材料清单` VARCHAR(255),
    `资助信息_奖学金` VARCHAR(255),
    `资助信息_生活补贴` VARCHAR(255),
    `住宿安排类型` VARCHAR(255),
    `文化适应资源` VARCHAR(255),
    `项目亮点标签` VARCHAR(255),
    `官方咨询渠道` VARCHAR(255),
    `原文信息` TEXT,
    `发布日期` DATE,
    `关键词` VARCHAR(255),
    `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `社团消息` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `类型` VARCHAR(50) NOT NULL,
    `标题` VARCHAR(255) NOT NULL,
    `消息子类` VARCHAR(50),
    `社团名称` VARCHAR(255) NOT NULL,
    `社团类别` VARCHAR(255),
    `活动类型` VARCHAR(50),
    `活动时间` VARCHAR(255),
    `活动地点` VARCHAR(255),
    `参与要求` VARCHAR(255),
    `特色标签` VARCHAR(255),
    `联系方式` VARCHAR(255),
    `原文信息` TEXT,
    `发布日期` DATE,
    `关键词` VARCHAR(255),
    `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `文体活动` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `类型` VARCHAR(50) NOT NULL,
    `标题` VARCHAR(255) NOT NULL,
    `活动开始时间` DATETIME,
    `活动结束时间` DATETIME,
    `活动地点` VARCHAR(255),
    `活动类型` VARCHAR(255),
    `主办单位` VARCHAR(255),
    `参与资格_年级` VARCHAR(255),
    `参与资格_学院` VARCHAR(255),
    `报名方式` VARCHAR(255),
    `报名截止时间` DATETIME,
    `费用金额` VARCHAR(50),
    `活动亮点` VARCHAR(255),
    `五育认定类型` VARCHAR(255),
    `线上参与链接` VARCHAR(255),
    `组队人数` VARCHAR(255),
    `原文信息` TEXT,
    `发布日期` DATE,
    `关键词` VARCHAR(255),
    `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `实践培训活动` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `类型` VARCHAR(50) NOT NULL,
    `标题` VARCHAR(255) NOT NULL,
    `活动开始时间` DATETIME,
    `活动结束时间` DATETIME,
    `活动地点` VARCHAR(255),
    `主办单位` VARCHAR(255),
    `活动形式` VARCHAR(255),
    `活动类型` VARCHAR(255),
    `实践内容` VARCHAR(255),
    `指导老师、讲师` VARCHAR(255),
    `参与对象_年级` VARCHAR(255),
    `参与对象_专业` VARCHAR(255),
    `报名截止时间` DATETIME,
    `费用金额` VARCHAR(50),
    `是否提供证书` BIT(1),
    `证书类型` VARCHAR(255),
    `五育认定类型` VARCHAR(255),
    `技能要求` VARCHAR(255),
    `课程亮点` VARCHAR(255),
    `报名方式` VARCHAR(255),
    `原文信息` TEXT,
    `发布日期` DATE,
    `关键词` VARCHAR(255),
    `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `作品征集` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `类型` VARCHAR(50) NOT NULL,
    `标题` VARCHAR(255) NOT NULL,
    `主办单位` VARCHAR(255),
    `征集开始时间` DATETIME,
    `提交截止时间` DATETIME,
    `作品主题` VARCHAR(255),
    `作品形式` VARCHAR(255),
    `内容要求` VARCHAR(255),
    `格式要求` VARCHAR(255),
    `参与资格_身份` VARCHAR(255),
    `参与资格_人数` VARCHAR(255),
    `提交渠道` VARCHAR(255),
    `奖励设置` VARCHAR(255),
    `成果应用` VARCHAR(255),
    `原文信息` TEXT,
    `发布日期` DATE,
    `关键词` VARCHAR(255),
    `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `其他活动` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `类型` VARCHAR(50) NOT NULL,
    `标题` VARCHAR(255) NOT NULL,
    `活动名称` VARCHAR(255) NOT NULL,
    `主办单位` VARCHAR(255),
    `活动起始时间` DATETIME,
    `活动结束时间` DATETIME,
    `地点` VARCHAR(255),
    `线上参会链接或腾讯会议号` VARCHAR(255),
    `活动类别` VARCHAR(255),
    `涉及领域` VARCHAR(255),
    `面向群体` VARCHAR(255),
    `核心内容` VARCHAR(255),
    `技能要求` VARCHAR(255),
    `报名截止时间` DATETIME,
    `报名方式` VARCHAR(255),
    `是否面试` BIT(1),
    `五育认定类型` VARCHAR(255),
    `携带材料` VARCHAR(255),
    `原文信息` TEXT,
    `发布日期` DATE,
    `关键词` VARCHAR(255),
    `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `实习就业` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `类型` VARCHAR(50) NOT NULL,
    `标题` VARCHAR(255) NOT NULL,
    `公司名称` VARCHAR(255),
    `工作地点` VARCHAR(255),
    `实习开始时间` DATETIME,
    `实习持续时间` VARCHAR(50),
    `申请截止日期` DATETIME,
    `招聘对象_年级` VARCHAR(255),
    `招聘对象_专业` VARCHAR(255),
    `学历要求` VARCHAR(255),
    `技能要求` VARCHAR(255),
    `工作内容` VARCHAR(255),
    `薪资待遇` VARCHAR(255),
    `公司福利` VARCHAR(255),
    `申请方式` VARCHAR(255),
    `是否提供转正机会` BIT(1),
    `笔试要求` VARCHAR(255),
    `面试要求` VARCHAR(255),
    `原文信息` TEXT,
    `发布日期` DATE,
    `关键词` VARCHAR(255),
    `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE TABLE `其他类型` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `类型` VARCHAR(50) NOT NULL,
    `标题` VARCHAR(255) NOT NULL,
    `内容分类` VARCHAR(255),
    `核心内容摘要` TEXT,
    `涉及对象` VARCHAR(255),
    `生效时间` DATETIME,
    `失效时间` VARCHAR(50),
    `行动截止时间` VARCHAR(50),
    `来源部门` VARCHAR(255),
    `来源层级` VARCHAR(50),
    `原文信息` TEXT,
    `发布日期` DATE,
    `关键词` VARCHAR(255),
    `原文链接` VARCHAR(255)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;